/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package ca.mattpayne.complainatronclient;

public final class R {
    public static final class array {
        public static final int number_complaints=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int anonymousCheckBox=0x7f06000f;
        public static final int cancelButton=0x7f06000d;
        public static final int cancelPrefsButton=0x7f060011;
        public static final int categorySpinner=0x7f060007;
        public static final int complaintCategoryText=0x7f060008;
        public static final int complaintDetailsTextView=0x7f060000;
        public static final int complaintText=0x7f06000b;
        public static final int complaintUserNameLabel=0x7f060009;
        public static final int complaintUserNameText=0x7f06000a;
        public static final int complaintsListView=0x7f060005;
        public static final int lblError=0x7f060004;
        public static final int mapView=0x7f060006;
        public static final int numberComplaintsSpinner=0x7f06000e;
        public static final int okButton=0x7f06000c;
        public static final int okPrefsButton=0x7f060010;
        public static final int voteAgainstButton=0x7f060002;
        public static final int voteForButton=0x7f060001;
        public static final int widget30=0x7f060003;
    }
    public static final class layout {
        public static final int complaint_details=0x7f030000;
        public static final int error=0x7f030001;
        public static final int main=0x7f030002;
        public static final int map_complaints=0x7f030003;
        public static final int new_complaint=0x7f030004;
        public static final int preferences=0x7f030005;
    }
    public static final class string {
        public static final int always_anonymous=0x7f050008;
        public static final int anonymous_submission=0x7f050006;
        public static final int api_key=0x7f050010;
        public static final int app_name=0x7f050003;
        public static final int close_button_text=0x7f050009;
        public static final int create_complaint_url=0x7f05000c;
        public static final int enter_complaint_category=0x7f050005;
        public static final int get_categories_url=0x7f05000e;
        public static final int get_complaints_url=0x7f05000d;
        public static final int map_label=0x7f050002;
        public static final int max_results=0x7f050011;
        public static final int new_complaint_label=0x7f050001;
        public static final int number_of_complaints_to_display_label=0x7f050007;
        public static final int preferences_label=0x7f050000;
        public static final int select_category_label=0x7f050004;
        public static final int vote_against_label=0x7f05000b;
        public static final int vote_for_label=0x7f05000a;
        public static final int vote_url=0x7f05000f;
    }
}
